### ISSUE TITLE
Change of name "ultrasphere"

### ISSUE THREAD

**Issue by thomleg50** [gaavin/ultrasphere#5]
Hello,
I allow your work not the problem.
What I Ask you is Change of name because it confuse users of respective project.
That's why I'm asking thé change of the name.
Thanks

**Comment by gaavin** [comment]
it is reloaded so no confusion.

**Comment by thomleg50** [comment]
Its a big Fuck for all dev who work for users.
Switch hacking is not a joke !

**Comment by fennectech** [comment]
But THIS is!
