### ISSUE TITLE
Your GBAtemp page got deleted

### ISSUE THREAD

**Issue by SirVertigo** [gaavin/ultrasphere#8]
HOES MAD
https://www.youtube.com/watch?v=J6oTIjvw_-8
![download](https://user-images.githubusercontent.com/34089801/61409275-cd76df00-a8d9-11e9-8d02-cf374d068fd1.png)

**Comment by SirVertigo** [comment]
i've been waiting, HOES MAD?

**Comment by gaavin** [comment]
don't care virign

**Comment by SirVertigo** [comment]
virgin*
